# Superstore Sales, Profit, and Customer Lifetime Value (CLV) Dashboard

## 📌 Introduction
This project delivers a professional Power BI dashboard that analyzes Superstore sales data with a focus on sales, profitability, discount behavior, customer segments, and Customer Lifetime Value (CLV). It enables stakeholders to make informed decisions through rich visualizations, drillthroughs, and scenario-based forecasting.

---

## 📊 Project Overview
The dashboard provides interactive insights into:
- Sales and profit performance over time
- Product and sub-category profitability
- Customer value through CLV analysis
- Discount strategies and their margin impact
- Forecasting and scenario simulation

---

## 🎯 Objectives
- Track sales and profitability KPIs  
- Calculate and visualize CLV across segments and regions  
- Analyze discount vs. profit relationships  
- Identify top products, customers, and regions  
- Enable product and region drillthrough insights  
- Reveal seasonality and forecast future trends  

---

## 🛠 Tools Used
- **Power BI** – Dashboard creation and DAX modeling  
- **Excel** – Initial data prep  
- **DAX** – CLV calculations, moving averages, KPIs  
- **Dataset** – [Download Superstore Dataset (Tableau)](https://www.tableau.com/sites/default/files/2021-05/Sample%20-%20Superstore.xls)

---

## 🧾 Dataset Description
~10,000 rows of historical transactions with fields like:  
- Order Date, Sales, Profit, Discount, Quantity  
- Product Name, Category, Sub-Category  
- Customer ID, Segment  
- Region, State  

---

## 🔧 Data Preparation
- Converted and formatted date fields  
- Created custom Date Table  
- Removed duplicates and ensured data consistency  
- Created calculated fields:  
  - Year, Month  
  - Gross Margin, Customer Lifespan  
  - CLV and CLV Segments (High, Mid, Low)  

---

## 📊 Exploratory Data Analysis (EDA)
- **Sales/Profit Over Time** (Line Chart)  
- **Discount vs. Profit** (Scatter)  
- **Sales by Category/Sub-Category** (Bar)  
- **Top 10 Products & Customers** (Bar)  
- **CLV Distribution** (Donut)  
- **Region Performance** (Map/Bar)  
- **Forecasting** using DAX-based trends  
- **Slicers** for dynamic filtering by Segment, Region, CLV Group, Date  

---

## 🧮 Key Metrics (KPIs)
- Total Sales  
- Total Profit  
- Avg Discount  
- Profit Margin  
- CLV = Avg Order Value × Frequency × Customer Lifespan  
- Adjusted CLV with What-If Economic Factor  

---

## 📈 Dashboard Highlights
- Executive KPI Cards  
- Interactive drillthrough pages (Product & Region)  
- Top N visuals for product/customer performance  
- Seasonality & forecasting charts  
- CLV comparison by segment/region  
- What-If analysis for economic sensitivity  

---

## 💡 Key Insights
- Technology is the most profitable category  
- Furniture suffers from over-discounting  
- West region leads in revenue and margin  
- Q4 sees peak seasonal performance  
- High-CLV customers drive >80% of profit  
- Discounts negatively affect margins  

---

## ✅ Recommendations
- Limit excessive discounting to improve margins  
- Focus retention efforts on high-CLV customers  
- Replicate successful regional strategies  
- Prepare inventory/marketing for Q4 spikes  
- Introduce loyalty programs and segmentation campaigns  

---

## 🧠 Conclusion
This dashboard bridges sales metrics with customer behavior and profitability. It enhances decision-making through clean visuals, CLV analysis, and forecasting tools—empowering retail teams to drive growth and improve customer value over time.

---
